### ISSUE TITLE
Train / test splits

### ISSUE THREAD

**Issue by vnmabus** [daviddiazvico/scikit-datasets#21]
Several repositories, such as the UCI or UCR, provide different datasets for train and test. Currently, we store these as separate attributes inside the Bunch object. This has several downsides:

* This approach mixes the data and the task (consider as an example OpenML where these concepts are well separated).
* Sometimes (most of the time?) the user is interested in the whole dataset, and not in the original task. Having to select and concatenate both attributes is confusing.
* If we want to support a `return_X_y` parameter this setup is confusing. Should we return only train, or a 4-tuple, breaking compatibility with scikit-learn?
* If we want to provide `as_frame`, would we need `frame` and `frame_test` attributes?
* If we want to provide `as_frame`, the names of the columns would be repeated in both dataframes (not very important, but still).

As an alternative, we could consider putting all data together and providing an attribute(s) with the indexes/size of the train/test data. Extracting the train/test sets would be trivial, if desired, and the normal behaviour would be to provide all the data as one attribute.

**Comment by vnmabus** [comment]
Please @daviddiazvico, have a look at this when you have time.

**Comment by daviddiazvico** [comment]
Hi @vnmabus . Sorry for the delay.

I like the alternative idea of putting all data together and providing the indexes of train/test/validation/etc. as separate attributes.

I'm afraid I don't have time to code this right now, but I'll be happy to review any PR.
