### ISSUE TITLE
Datasets are downloaded even if they are already in disk

### ISSUE THREAD

**Issue by vnmabus** [daviddiazvico/scikit-datasets#23]
I have seen that almost every repo uses `urlretrieve` to download the data, instead of the functions in `.base` that check first if the data is not already downloaded. The only exceptions are the repos that I contributed: `cran` and `ucr`. Is this a bug, @daviddiazvico?

**Comment by daviddiazvico** [comment]
Probably it is. If you want to, please feel free to fix it. You just need to change all references to ``urlretrieve`` by references to ``base.fetch_*``, am I right?
