### ISSUE TITLE
Raetsch data have matrix target

### ISSUE THREAD

**Issue by vnmabus** [daviddiazvico/scikit-datasets#26]
It seems that target data from Raetsch is bidimensional, even when the second dimension is 1. I am not sure if there are datasets which are multitarget or not, but I think that for datasets with only one target the target should be a vector, not a column matrix. @daviddiazvico , what do you think?

**Comment by daviddiazvico** [comment]
I agree. If I remember correctly, all Raetsch's datasets are binary classification.

**Comment by vnmabus** [comment]
Solved in #35.
